### ISSUE TITLE
怎么集成到相机上面

### ISSUE THREAD

**Issue by 704480904** [wangpeiyuan/ZxingBarCode#1]
怎么集成到相机上面  我想集成两种扫描方式，因为二维码有时候用Zxing扫描太慢 ，用相机获取到Bitmap 只后再调用 示例中的代码解析么？

**Comment by wangpeiyuan** [comment]
目前这个库没有提供扫描功能，已经有很多不错的第三方做了相关的功能。不用获取 bitmap 再解析啊，获取到相机的帧数据就可以直接解析了。
